version: '3.8'

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile-app
    env_file:
      .env
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./src:/usr/app/src
    depends_on:
      - db
    restart: always
  db:
    container_name: db
    build:
      context: ./database
      dockerfile: Dockerfile-db
    image: postgres
    hostname: ${POSTGRES_HOST}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_HOST: ${POSTGRES_HOST}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - postgress-logs:/var/log/postgresql
    restart: always

volumes:
  postgres-data:
  postgress-logs:

networks:
  default:
    driver: bridge