version: '3.8'

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: app.Dockerfile
    env_file:
      .env
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
    networks:
      - hls
    restart: always
    develop:
      watch:
        - action: rebuild
          path: ./src
          target: /app/src
  seeder:
    container_name: seeder
    build:
      context: .
      dockerfile: seeder.Dockerfile
    env_file:
      .env
    networks:
      - hls
    depends_on:
      - db
    restart: on-failure
  db:
    container_name: db
    build:
      context: .
      dockerfile: db.Dockerfile
    image: postgres:16.2-alpine
    hostname: ${POSTGRES_HOST_DOCKER}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_HOST: ${POSTGRES_HOST}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - postgress-logs:/var/log/postgresql
    command: ["postgres", "-c", "logging_collector=on", "-c", "log_directory=/var/log/postgresql", "-c", "log_filename=postgresql.log", "-c", "log_statement=all"]
    networks:
      - hls
    restart: always

volumes:
  postgres-data:
  postgress-logs:

networks:
  hls:
    driver: bridge