version: '3.8'

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: app.Dockerfile
    env_file:
      .env
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
    networks:
      - hls
    restart: always
    develop:
      watch:
        - action: rebuild
          path: ./src
          target: /app/src
  db:
    container_name: db
    build:
      context: .
      dockerfile: db.Dockerfile
    image: postgres:16.2-alpine
    hostname: ${POSTGRES_HOST}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    env_file:
      .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - postgress-logs:/var/log/postgresql
    networks:
      - hls
    restart: always

volumes:
  postgres-data:
  postgress-logs:

networks:
  hls:
    driver: bridge